services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:

    KimaiPlugin\VacationHoursBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'
