version: '3.7'

services:
  kimai:
    image: kimai/kimai2:apache
    container_name: kimai
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://kimai:kimai@db/kimai
    ports:
      - "8001:8001"
    volumes:
      - ./to-copy:/opt/kimai/var/plugins
      # - ./to-copy-root:/opt/kimai
    working_dir: /opt/kimai 
    depends_on:
      - db

  db:
    image: mariadb:10.5.8
    container_name: kimai_db
    environment:
      - MYSQL_ROOT_PASSWORD=kimai
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=kimai
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
